version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-service:
    networks:
      default:
        aliases:
          - config-service
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: config-service
    ports:
      - 8888:8888
    image: config-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: registry-service
    image: registry-service
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: gateway-service
    image: gateway-service
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    networks:
      default:
        aliases:
          - auth-service
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: auth-service
    image: auth-service
    restart: always
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: mongodb
    image: mongodb
    restart: always
    ports:
      - 25000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: account-service
    build: account-service
    restart: always
    ports:
      - 6000:6000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: mongodb
    image: mongodb
    ports:
      - 26000:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

#  statistics-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      MONGODB_PASSWORD: $MONGODB_PASSWORD
#      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-statistics-service
#    restart: always
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
#
#  statistics-mongodb:
#    environment:
#      MONGODB_PASSWORD: $MONGODB_PASSWORD
#    image: sqshq/piggymetrics-mongodb
#    restart: always
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
#
#  notification-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      MONGODB_PASSWORD: $MONGODB_PASSWORD
#      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-notification-service
#    restart: always
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
#
#  notification-mongodb:
#    image: sqshq/piggymetrics-mongodb
#    restart: always
#    environment:
#      MONGODB_PASSWORD: $MONGODB_PASSWORD
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
#
#  monitoring:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-monitoring
#    restart: always
#    ports:
#      - 9000:8080
#      - 8989:8989
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"