spring:
  data:
    mongodb:
      host: auth-mongodb
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: bearinkitchen
      port: 27017

server:
  context-path: /uaa
port: 5000